version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - './frontend/.env'
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - './backend/.env'
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: favxlaw
      POSTGRES_PASSWORD: favxlaw24
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
      image: adminer:latest
      restart: always
      ports:
        - 8080:8080
      environment:
        ADMINER_DEFAULT_SERVER: db
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: ./Dockerfile
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #     - backend
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '8090:81'
      - '80:80'
      - '443:443'
    environment:
      DB_SQLITE_FILE: "/data/db.sqlite"
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
volumes:
  db_data: