version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: hng-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: my-backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=my-app
      - POSTGRES_USER=favxlaw
      - POSTGRES_PASSWORD=favxlaw24
      - FIRST_SUPERUSER=favxlaw@gmail.com
      - FIRST_SUPERUSER_PASSWORD=favxlaw23
      - PROJECT_NAME=hng-project
      - BACKEND_CORS_ORIGINS="http://localhost,http://localhost:5173,https://localhost,https://localhost:5173"
      - SECRET_KEY=changethis123
      - USERS_OPEN_REGISTRATION=True
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: favxlaw
      POSTGRES_PASSWORD: favxlaw24
      POSTGRES_DB: my-app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    command: ["/bin/sh", "-c", "rm /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]  
    depends_on: 
      - frontend
      - backend   

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 8090:81
      - 80:80
      - 443:443
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt 

volumes:
  postgres_data:
